name: Run Python Tests & Check Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  # === Job for Project 1 ===
  project-1-test:
    if: ${{ startsWith(github.head_ref, 'project-1') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pytest
      - name: Run Pytest for Project 1
        # Run pytest ONLY on the specific project folder
        run: pytest -v 01-unit-testing-calculator/

  # === Job for Project 2 ===
  project-2-test:
    if: ${{ startsWith(github.head_ref, 'project-2') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pytest requests
      - name: Run Pytest for Project 2
        run: pytest -v 02-api-testing-omdb/

  # === Job for Project 3 ===
  project-3-test:
    if: ${{ startsWith(github.head_ref, 'project-3') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pytest selenium
      - name: Run Pytest for Project 3
        run: pytest -v 03-ui-testing-selenium/

  # === Job for Project 4 ===
  project-4-coverage-test:
    if: ${{ startsWith(github.head_ref, 'project-4') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests selenium flask pytest-cov gunicorn
      - name: Run Pytest with Coverage Check
        run: |
          cd 04-e2e-testing-todo-app
          gunicorn app:app --daemon
          sleep 3
          cd ..
          pytest -v --cov=04-e2e-testing-todo-app/app --cov-fail-under=85 04-e2e-testing-todo-app/
