name: Run Python Tests & Check Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  # === Job for Project 1 ===
  project-1-test:
    if: ${{ startsWith(github.head_ref, 'project-1') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pytest
      - name: Run Pytest for Project 1
        run: |
          # Change directory into the project folder first
          cd Projects/unit-testing-calculator-01
          # Now run pytest from inside the folder
          pytest -v

  # === Job for Project 2 ===
  project-2-test:
    if: ${{ startsWith(github.head_ref, 'project-2') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pytest requests
      - name: Run Pytest for Project 2
        run: |
          # Change directory into the project folder
          cd Projects/api-testing-omdb-02
          pytest -v

  # === Job for Project 3 ===
  project-3-test:
    if: ${{ startsWith(github.head_ref, 'project-3') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pytest selenium
      - name: Run Pytest for Project 3
        run: |
          # Change directory into the project folder
          cd Projects/ui-testing-selenium-03
          pytest -v

  # === Job for Project 4 ===
  project-4-coverage-test:
    if: ${{ startsWith(github.head_ref, 'project-4') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests selenium flask pytest-cov gunicorn
      - name: Run Pytest with Coverage Check
        run: |
          # Go into the project 4 folder
          cd Projects/e2e-testing-todo-app-04
          # Start the server in the background
          gunicorn app:app --daemon
          sleep 3 # Wait for server to start
          # Run tests from inside the folder
          pytest -v --cov=app --cov-fail-under=85
